name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - nltk
  - spacy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - wordcloud
    - textblob
